const quotes = [
    'Sempre vença suas batalhas',
    'Nunca os deixe rir de você',
    'Sempre descanse',
    'Esqueça o seu passado',
    'Força bate força',
    'Seu próprio destino',
    'Não lamente os mortos',
    'Viaje sozinho',
    'Mantenha sua casa arrumada',
    'Mantenha sua arma afiada',
    'Mães sempre o trairão',
    'Mantenha sua capa seca',
    'Nunca tenha medo',
    'Respeite seus superiores',
    'Um inimigo, um golpe',
    'Não hesite',
    'Acredite na sua força',
    'Busque a verdade na escuridão',
    'Se você tentar, tenha sucesso',
    'Fale apenas a verdade',
    'Esteja ciente de seu entorno',
    'Abandone o ninho',
    'Identifique o ponto fraco do inimigo',
    'Atinja o ponto fraco do inimigo',
    'Proteja seu próprio ponto fraco',
    'Não confie no seu reflexo',
    'Coma o máximo que puder',
    'Não olhe para a escuridão',
    'Desenvolva seu senso de direção',
    'Nunca aceite uma promessa',
    'A doença vive dentro da sujeira',
    'Os nomes têm poder',
    'Não mostre respeito ao inimigo',
    'Não coma imediatamente antes de dormir',
    'Pra cima é pra cima, pra baixo é pra baixo',
    'Cascas de ovos são quebradiças',
    'Pegue emprestado, mas não empreste',
    'Cuidado com a força misteriosa',
    'Coma rapidamente e beba devagar',
    'Não obedeça a nenhuma lei, a não ser a sua',
    'Aprenda a detectar mentiras',
    'Gaste geo quando você o tiver',
    'Nunca perdoe',
    'Você não pode respirar água',
    'Uma coisa não é outra',
    'O mundo é menor do que você pensa',
    'Crie sua própria arma',
    'Cuidado com o fogo',
    'Estátuas não têm sentido',
    'Não se demore nos mistérios',
    'Nada é inofensivo',
    'Cuidado com o ciúme dos pais',
    'Não roube os desejos dos outros',
    'Se você bloquear algo, guarde a chave',
    'Curve-se a ninguém',
    'Não Sonhe',
    'Obedeça a todos os preceitos'
];
const quote_phrase = {
    'Sempre vença suas batalhas': "Perder uma batalha significa que você não ganha nada e não ensina nada. Vença suas batalhas ou não se envolva nelas!",
    'Nunca os deixe rir de você': "Os tolos riem de tudo, até de seus superiores. Mas cuidado, o riso não é inofensivo! O riso se espalha como uma doença e logo todos estão rindo de você. Você precisa atacar a fonte dessa alegria perversa rapidamente para impedir que ela se espalhe.",
    'Sempre descanse': "Lutas e aventuras têm seu preço em seu corpo. Quando você descansa, seu corpo se fortalece e se repara. Quanto mais você descansa, mais forte se torna.",
    'Esqueça o seu passado': "O passado é doloroso, e pensar no seu passado só pode lhe trazer miséria. Pense em outra coisa, como o futuro, ou alguma comida.",
    'Força bate força': "Seu oponente é forte? Não importa! Simplesmente supere sua força com ainda mais força, e logo eles serão derrotados.",
    'Seu próprio destino': "Nossos anciãos ensinam que nosso destino é escolhido para nós antes mesmo de nascermos. Discordo.",
    'Não lamente os mortos': "Quando morremos, as coisas ficam melhores para nós ou piores? Não há como dizer, então não devemos nos preocupar com o luto. Ou comemorando.",
    'Viaje sozinho': "Você não pode confiar em ninguém, e ninguém será sempre leal. Portanto, ninguém deve ser seu companheiro constante.",
    'Mantenha sua casa arrumada': "Sua casa é onde você mantém seu bem mais precioso - você mesmo. Portanto, você deve fazer um esforço para mantê-lo agradável e limpo.",
    'Mantenha sua arma afiada': "Garanto que minha arma, 'Life Ender', seja mantida afiada o tempo todo. Isso facilita muito o corte de coisas.",
    'Mães sempre o trairão': "Este preceito se explica.",
    'Mantenha sua capa seca': "Se a sua capa ficar molhada, seque-a assim que puder. Usar mantos molhados é desagradável e pode levar a doenças.",
    'Nunca tenha medo': "O medo só pode te impedir. Enfrentar seus medos pode ser um esforço tremendo. Portanto, você não deve ter medo em primeiro lugar.",
    'Respeite seus superiores': "Se alguém é seu superior em força, intelecto ou ambos, você precisa demonstrar respeito. Não os ignore ou ria deles.",
    'Um inimigo, um golpe': "Você só deve usar um único golpe para derrotar um inimigo. Mas é um desperdício. Além disso, contando seus golpes enquanto luta, você saberá quantos inimigos derrotou.",
    'Não hesite': "Depois de tomar uma decisão, execute-a e não olhe para trás. Você conseguirá muito mais dessa maneira.",
    'Acredite na sua força': "Outros podem duvidar de você, mas há alguém em quem você sempre pode confiar. Você mesmo. Certifique-se de acreditar em sua própria força, e você nunca vacilará.",
    'Busque a verdade na escuridão': "Este preceito também se explica.",
    'Se você tentar, tenha sucesso': "Se você estiver tentando algo, certifique-se de alcançá-lo. Se você não conseguir, você realmente falhou! Evite isso a todo custo.",
    'Fale apenas a verdade': "Ao falar com alguém, é cortês e também eficiente falar com sinceridade. Cuidado, porém, que falar de verdade pode torná-lo inimigo. Isso é algo que você terá que suportar.",
    'Esteja ciente de seu entorno': "Não ande apenas olhando para o chão! Você precisa olhar de vez em quando, para garantir que nada o surpreenda.",
    'Abandone o ninho': "Assim que pude, deixei meu local de nascimento e fiz meu caminho para o mundo. Não permaneça no ninho. Não há nada para você lá.",
    'Identifique o ponto fraco do inimigo': "Todo inimigo que você encontra tem um ponto fraco, como uma rachadura na concha ou estar dormindo. Você deve estar constantemente alerta e examinando seu inimigo para detectar sua fraqueza!",
    'Atinja o ponto fraco do inimigo': "Depois de identificar o ponto fraco do seu inimigo, de acordo com o preceito anterior, atinja-o. Isso irá destruí-los instantaneamente.",
    'Proteja seu próprio ponto fraco': "Esteja ciente de que seu inimigo tentará identificar seu ponto fraco, então você deve protegê-lo. A melhor proteção? Nunca tendo um ponto fraco em primeiro lugar.",
    'Não confie no seu reflexo': "Ao olhar para certas superfícies brilhantes, você poderá ver uma cópia do seu próprio rosto. O rosto imitará seus movimentos e parecerá com o seu, mas não creio que possa ser confiável.",
    'Coma o máximo que puder': "Ao fazer uma refeição, coma o máximo que puder. Isso fornece energia extra e significa que você pode comer com menos frequência.",
    'Não olhe para a escuridão': "Se você olhar para a escuridão e não puder ver nada por muito tempo, sua mente começará a ficar com as memórias antigas. Memórias devem ser evitadas, conforme o Preceito Quatro.",
    'Desenvolva seu senso de direção': "É fácil se perder ao viajar por cavernas sinuosas e sinuosas. Ter um bom senso de direção é como ter um mapa mágico dentro da sua cabeça. Muito útil.",
    'Nunca aceite uma promessa': "Despreze as promessas dos outros, pois elas sempre são quebradas. Promessas de amor ou noivado devem ser evitadas especialmente.",
    'A doença vive dentro da sujeira': "Você ficará doente se passar muito tempo em lugares sujos. Se você estiver hospedado na casa de outra pessoa, exija o mais alto nível de limpeza do seu host.",
    'Os nomes têm poder': "Os nomes têm poder, e assim nomear algo é conceder-lhe poder. Eu mesmo nomeei minha unha como 'Life Ender'. Não roube o nome que eu inventei! Invente o seu!",
    'Não mostre respeito ao inimigo': "Ser galante com seus inimigos não é virtude! Se alguém se opõe a você, não merece respeito, bondade ou misericórdia.",
    'Não coma imediatamente antes de dormir': "Isso pode causar inquietação e indigestão. É apenas senso comum.",
    'Pra cima é pra cima, pra baixo é pra baixo': "Se você cair na escuridão, pode ser fácil perder o rumo e esquecer o caminho a seguir. Mantenha esse preceito em mente!",
    'Cascas de ovos são quebradiças': "Mais uma vez, esse preceito se explica.",
    'Pegue emprestado, mas não empreste': "Se você empresta e é pago, não ganha nada. Se você empresta, mas não paga, você ganha tudo.",
    'Cuidado com a força misteriosa': "Uma força misteriosa incide sobre nós de cima, empurrando-nos para baixo. Se você ficar muito tempo no ar, a força o esmagará contra o chão e o destruirá. Cuidado!",
    'Coma rapidamente e beba devagar': "Seu corpo é uma coisa delicada e você deve alimentá-lo com grande deliberação. A comida deve ser consumida o mais rápido possível, mas os líquidos são mais lentos.",
    'Não obedeça a nenhuma lei, a não ser a sua': "Leis escritas por outras pessoas podem incomodá-lo ou ser um fardo. Deixe seus próprios desejos serem a única lei.",
    'Aprenda a detectar mentiras': "Quando outros falam, geralmente mentem. Examine e questione-os incansavelmente até que eles revelem seu engano.",
    'Gaste geo quando você o tiver': "Alguns se apegam ao seu Geo, levando-o até a terra quando morrem. É melhor gastá-lo quando puder, para que você possa desfrutar de várias coisas na vida.",
    'Nunca perdoe': "Se alguém lhe pedir perdão, por exemplo, um irmão seu, sempre negue. Aquele irmão, ou quem quer que seja, não merece isso.",
    'Você não pode respirar água': "A água é refrescante, mas se você tentar respirar, ficará em choque.",
    'Uma coisa não é outra': "Este deve ser óbvio, mas outros já tentaram argumentar que uma coisa, que é claramente o que é e não outra, é realmente outra coisa, o que não é. Fique em guarda!",
    'O mundo é menor do que você pensa': "Quando jovem, você tende a pensar que o mundo é vasto, enorme, gigantesco. É natural. Infelizmente, é realmente muito menor que isso. Posso dizer isso, agora tendo viajado por toda parte na terra.",
    'Crie sua própria arma': "Só você sabe exatamente o que é necessário em sua arma. Eu mesmo criei 'Life Ender' a partir de casca de árvore em tenra idade. Nunca falhou comigo. Nem eu.",
    'Cuidado com o fogo': "O fogo é um tipo de espírito quente que dança de forma imprudente. Ele pode aquecê-lo e fornecer luz, mas também queimará sua concha se ela se aproximar demais.",
    'Estátuas não têm sentido': "Não os honre! Ninguém jamais fez uma estátua sua ou de você, então por que devemos prestar atenção?",
    'Não se demore nos mistérios': "Algumas coisas neste mundo nos parecem quebra-cabeças. Ou enigmas. Se o significado por trás de algo não for imediatamente evidente, não perca tempo pensando sobre isso. Apenas siga em frente.",
    'Nada é inofensivo': "Dada a chance, tudo neste mundo vai machucá-lo. Amigos, inimigos, monstros, caminhos irregulares. Suspeite de todos eles.",
    'Cuidado com o ciúme dos pais': "Os pais acreditam que, porque nos criaram, devemos servi-los e nunca exceder suas capacidades. Se você deseja seguir seu próprio caminho, deve vencer seu pai. Ou simplesmente abandoná-lo.",
    'Não roube os desejos dos outros': "Toda criatura mantém seus desejos trancados dentro de si. Se você vislumbrar os desejos de outra pessoa, resista ao desejo de reivindicá-los como seus. Não o levará à felicidade.",
    'Se você bloquear algo, guarde a chave': "Nada deve ficar trancado para sempre, então segure suas chaves. Você retornará e desbloqueará tudo o que escondeu.",
    'Curve-se a ninguém': "Existem pessoas neste mundo que imporiam sua vontade a outros. Eles reivindicam propriedade sobre sua comida, sua terra, seu corpo e até seus pensamentos! Eles não fizeram nada para ganhar essas coisas. Nunca se curve a eles e desobedeça seus comandos.",
    'Não Sonhe': "Sonhos são coisas perigosas. Idéias estranhas, não as suas, podem invadir sua mente. Mas se você resistir a essas idéias, a doença estragará seu corpo! Melhor não sonhar, como eu.",
    'Obedeça a todos os preceitos': "Mais importante, você deve comprometer todos esses preceitos para a memória e obedecer a todos. Incluindo este!"
};
const date_now = new Date().getDate() + '/' + (new Date().getMonth() + 1) + '/' + new Date().getFullYear();


function setQuote(qnum) {
    document.getElementById("date").innerHTML = `${date_now}`;
    document.getElementById("title").innerHTML = `${qnum}º. ${quotes[qnum]}`;
    document.getElementById("quote").innerHTML = quote_phrase[quotes[qnum]];
}


if(localStorage.getItem('zoteday') && localStorage.getItem('zoteday') == date_now) {
    setQuote(localStorage.getItem('zotequote'));
}
else {
    const qnumber = Math.round(Math.random() * 56);
    setQuote(qnumber);
    localStorage.setItem('zoteday', date_now);
    localStorage.setItem('zotequote', qnumber);
}